/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    Field: typeof import('./components/Field.vue')['default']
    FieldGroup: typeof import('./components/FieldGroup.vue')['default']
    Fieldset: typeof import('./components/Fieldset.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Option: typeof import('./components/Option.vue')['default']
    Options: typeof import('./components/Options.vue')['default']
    Radio: typeof import('./components/Radio.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    Textarea: typeof import('./components/Textarea.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
